#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\PageController::index

article_show:
  path: /afficher/{url}
  controller: App\Controller\PageController::afficher
